"""
Step 5: Extract operating cash flow and capital expenditures, then calculate
free cash flow.

This script loads cached SEC EDGAR company facts, extracts annual and quarterly
operating cash flow and capital expenditures, calculates free cash flow, saves
annual results to CSV, and compares two companies on one annual FCF chart.

Formula:
    free cash flow = operating cash flow - capital expenditures

Important:
    The capex tags used here normally report cash outflows as positive values.
    That is why capex is subtracted from operating cash flow.

Metrics produced:
    - Annual operating cash flow
    - Annual capital expenditures
    - Annual free cash flow
    - Quarterly free cash flow

Output:
    Annual CSV files are saved by save_csv(), normally into edgar_output/.

    The comparison chart is saved by plot_compare(), normally as:

        edgar_output/fcf_annual.png

Caution:
    Free cash flow is not a standardized GAAP metric. Different analysts may
    define it differently, and companies may use different XBRL tags for capex.
    Important values should be checked against the original cash flow statement.
"""

from edgar_utils import load_facts, flow_series, save_csv, plot_compare


# US-GAAP tag commonly used for cash generated by operating activities.
OCF_TAG = "NetCashProvidedByUsedInOperatingActivities"

# Candidate US-GAAP tags for capital expenditures.
#
# Different companies may use different concepts for purchases of property,
# plant, equipment, or other productive assets.
CAPEX_TAGS = [
    "PaymentsToAcquirePropertyPlantAndEquipment",
    "PaymentsToAcquireProductiveAssets",
]


def build(t):
    """Build annual and quarterly free-cash-flow series for one ticker.

    Parameters
    ----------
    t:
        Stock ticker symbol, such as "AAPL" or "MSFT".

    Returns
    -------
    tuple
        A tuple containing:

        - annual free-cash-flow series
        - quarterly free-cash-flow series

    Notes
    -----
    Operating cash flow is extracted using OCF_TAG.

    Capital expenditures are extracted using CAPEX_TAGS because companies may
    use different XBRL tags for similar investing cash outflows.

    Free cash flow is calculated as:

        operating cash flow - capital expenditures

    Capex values are assumed to be reported as positive outflow amounts.
    """
    # Load the cached SEC company-facts JSON for the selected ticker.
    # If no cached file exists yet, load_facts() may download it first.
    f = load_facts(t)

    # Extract annual and quarterly operating cash flow.
    ocf_a, ocf_q = flow_series(f, OCF_TAG)

    # Extract annual and quarterly capital expenditures.
    #
    # CAPEX_TAGS is a list because companies may use different XBRL concepts.
    cap_a, cap_q = flow_series(f, CAPEX_TAGS)

    # Calculate annual free cash flow.
    #
    # If capex is missing for a date, this code uses zero. That preserves the
    # operating-cash-flow date, but the result should be treated cautiously
    # because missing capex data does not necessarily mean capex was zero.
    fcf_a = {d: ocf_a[d] - cap_a.get(d, 0) for d in ocf_a}

    # Calculate quarterly free cash flow using the same approach.
    fcf_q = {d: ocf_q[d] - cap_q.get(d, 0) for d in ocf_q}

    # Save annual operating cash flow, capex, and free cash flow to CSV.
    #
    # A blank capex cell is written when no matching capex value is available.
    save_csv(
        f"{t}_annual_fcf.csv",
        [
            "fiscal_year_end",
            "operating_cash_flow_usd",
            "capex_usd",
            "free_cash_flow_usd",
        ],
        [
            [
                d,
                ocf_a[d],
                cap_a.get(d, ""),
                fcf_a[d],
            ]
            for d in sorted(ocf_a)
        ],
    )

    # Return annual and quarterly FCF series for charts or further analysis.
    return fcf_a, fcf_q


if __name__ == "__main__":
    # Companies selected for the comparison.
    pair = ["AAPL", "MSFT"]

    # Build annual free-cash-flow data for each company.
    #
    # build(t) returns:
    #     (annual free cash flow, quarterly free cash flow)
    #
    # [0] selects the annual series used in this chart.
    data = {t: build(t)[0] for t in pair}

    # Plot both companies' annual free cash flow on the same chart.
    #
    # billions=True tells plot_compare() to display values in billions of USD.
    plot_compare(
        data,
        f"{pair[0]} vs {pair[1]}: free cash flow (annual)",
        "FCF ($B)",
        "fcf_annual.png",
        billions=True,
    )
